/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Details;
import model.DetailsHistory;

/**
 *
 * @author samhitha
 */
public class SearchJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchJPanel
     */
    DetailsHistory history;
    
    public SearchJPanel(DetailsHistory history) {
        initComponents();
        
        this.history=history;
        
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        createjLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        viewButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        phonejText = new javax.swing.JTextField();
        photojLabel = new javax.swing.JLabel();
        genderjText = new javax.swing.JTextField();
        namejText = new javax.swing.JTextField();
        idjText = new javax.swing.JTextField();
        agejText = new javax.swing.JTextField();
        datejText = new javax.swing.JTextField();
        agejLabel = new javax.swing.JLabel();
        leveljText = new javax.swing.JTextField();
        genderjLabel = new javax.swing.JLabel();
        tinfojText = new javax.swing.JTextField();
        datejLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        leveljLabel = new javax.swing.JLabel();
        titlejText = new javax.swing.JTextField();
        tinfojLabel = new javax.swing.JLabel();
        emailjText = new javax.swing.JTextField();
        titlejLabel = new javax.swing.JLabel();
        contactjLabel = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        phonejLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        createjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        createjLabel.setText("VIEW EMPLOYEE DETAILS");

        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Age", "Gender", "Start Date", "Level", "Team Info", "Position Title", "Number", "Email"
            }
        ));
        jScrollPane1.setViewportView(detailsTable);

        viewButton.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        viewButton.setText("View");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        photojLabel.setText("Photo:");

        namejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextActionPerformed(evt);
            }
        });

        idjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextActionPerformed(evt);
            }
        });

        agejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextActionPerformed(evt);
            }
        });

        agejLabel.setText("Age:");

        genderjLabel.setText("Gender:");

        tinfojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinfojTextActionPerformed(evt);
            }
        });

        datejLabel.setText("Start Date:");

        namejLabel.setText("Name:");

        leveljLabel.setText("Level:");

        tinfojLabel.setText("Team Info:");

        titlejLabel.setText("Position Title:");

        contactjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        contactjLabel.setText("Contact Info");

        idjLabel.setText("Employee ID:");

        phonejLabel.setText("Phone Number:");

        emailjLabel.setText("Email:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 888, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(37, 37, 37)
                .addComponent(deleteButton)
                .addGap(215, 215, 215))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contactjLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(phonejLabel)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(agejLabel)
                                                .addComponent(idjLabel)
                                                .addComponent(namejLabel)
                                                .addComponent(genderjLabel)
                                                .addComponent(datejLabel)
                                                .addComponent(leveljLabel)
                                                .addComponent(tinfojLabel))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(72, 72, 72)
                                                .addComponent(emailjLabel))))
                                    .addComponent(titlejLabel)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(photojLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(phonejText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titlejText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agejText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namejText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datejText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(leveljText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idjText)
                                    .addComponent(emailjText)
                                    .addComponent(genderjText)
                                    .addComponent(tinfojText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(createjLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(createjLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(idjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(agejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejLabel)
                    .addComponent(namejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderjLabel)
                    .addComponent(genderjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejLabel)
                    .addComponent(datejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leveljLabel)
                    .addComponent(leveljText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinfojLabel)
                    .addComponent(tinfojText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlejLabel)
                    .addComponent(titlejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonejLabel)
                    .addComponent(phonejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailjLabel)
                    .addComponent(emailjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(photojLabel)
                .addContainerGap(250, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = detailsTable.getSelectedRow();
        if (selectedRowIndex<0) {
            JOptionPane.showMessageDialog(this,"Please select row to delete.");
            return;
        }
        DefaultTableModel model= (DefaultTableModel) detailsTable.getModel();
        Details selectedDetails = (Details) model.getValueAt(selectedRowIndex, 0);

        namejText.setText(selectedDetails.getName());
        idjText.setText(selectedDetails.getId());
        agejText.setText(String.valueOf(selectedDetails.getAge()));
        genderjText.setText(selectedDetails.getGender());
        datejText.setText(selectedDetails.getDate());
        leveljText.setText(selectedDetails.getLevel());
        tinfojText.setText(selectedDetails.getInfo());
        titlejText.setText(selectedDetails.getTitle());
        phonejText.setText(selectedDetails.getPhone());
        emailjText.setText(selectedDetails.getEmail());

    }//GEN-LAST:event_viewButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = detailsTable.getSelectedRow();
        if (selectedRowIndex<0) {
            
            JOptionPane.showMessageDialog(this,"Please select row to delete.");
            return;
        }
        
        DefaultTableModel model= (DefaultTableModel) detailsTable.getModel();
        Details selectedDetails = (Details) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteDetails(selectedDetails);
        
        JOptionPane.showMessageDialog(this,"Details deleted.");
        populateTable();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void namejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextActionPerformed

    private void idjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextActionPerformed

    private void agejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextActionPerformed

    private void tinfojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinfojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinfojTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agejLabel;
    private javax.swing.JTextField agejText;
    private javax.swing.JLabel contactjLabel;
    private javax.swing.JLabel createjLabel;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JTextField datejText;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JTextField genderjText;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leveljLabel;
    private javax.swing.JTextField leveljText;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejText;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JTextField phonejText;
    private javax.swing.JLabel photojLabel;
    private javax.swing.JLabel tinfojLabel;
    private javax.swing.JTextField tinfojText;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JTextField titlejText;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        DefaultTableModel model= (DefaultTableModel) detailsTable.getModel();
        model.setRowCount(0);
        
        for (Details ds : history.getHistory()) {
            Object[] row = new Object[10];
            row[0] = ds;
            row[1] = ds.getId();
            row[2] = ds.getAge();
            row[3] = ds.getGender();
            row[4] = ds.getDate();
            row[5] = ds.getLevel();
            row[6] = ds.getInfo();
            row[7] = ds.getTitle();
            row[8] = ds.getPhone();
            row[9] = ds.getEmail();
            
            model.addRow(row);
            
        }
    }
}
