/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Details;
import model.DetailsHistory;

/**
 *
 * @author samhitha
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */ 
    DetailsHistory history;
    
    public CreateJPanel(DetailsHistory history) {
        initComponents();
        this.history = history;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        phonejText = new javax.swing.JTextField();
        genderjText = new javax.swing.JTextField();
        namejText = new javax.swing.JTextField();
        idjText = new javax.swing.JTextField();
        agejText = new javax.swing.JTextField();
        datejText = new javax.swing.JTextField();
        agejLabel = new javax.swing.JLabel();
        leveljText = new javax.swing.JTextField();
        genderjLabel = new javax.swing.JLabel();
        tinfojText = new javax.swing.JTextField();
        datejLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        leveljLabel = new javax.swing.JLabel();
        titlejText = new javax.swing.JTextField();
        tinfojLabel = new javax.swing.JLabel();
        emailjText = new javax.swing.JTextField();
        titlejLabel = new javax.swing.JLabel();
        createjLabel = new javax.swing.JLabel();
        contactjLabel = new javax.swing.JLabel();
        idjLabel = new javax.swing.JLabel();
        phonejLabel = new javax.swing.JLabel();
        emailjLabel = new javax.swing.JLabel();
        SavejButton = new javax.swing.JButton();

        namejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namejTextActionPerformed(evt);
            }
        });

        idjText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjTextActionPerformed(evt);
            }
        });

        agejText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextActionPerformed(evt);
            }
        });

        agejLabel.setText("Age:");

        genderjLabel.setText("Gender:");

        tinfojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinfojTextActionPerformed(evt);
            }
        });

        datejLabel.setText("Start Date:");

        namejLabel.setText("Name:");

        leveljLabel.setText("Level:");

        tinfojLabel.setText("Team Info:");

        titlejLabel.setText("Position Title:");

        createjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        createjLabel.setText("ENTER EMPLOYEE DETAILS");

        contactjLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        contactjLabel.setText("Contact Info");

        idjLabel.setText("Employee ID:");

        phonejLabel.setText("Phone Number:");

        emailjLabel.setText("Email:");

        SavejButton.setFont(new java.awt.Font("Helvetica Neue", 3, 12)); // NOI18N
        SavejButton.setText("Save");
        SavejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(createjLabel))
                    .addComponent(contactjLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(phonejLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(agejLabel)
                                        .addComponent(idjLabel)
                                        .addComponent(namejLabel)
                                        .addComponent(genderjLabel)
                                        .addComponent(datejLabel)
                                        .addComponent(leveljLabel)
                                        .addComponent(tinfojLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(72, 72, 72)
                                        .addComponent(emailjLabel))))
                            .addComponent(titlejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SavejButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(phonejText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titlejText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(agejText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(namejText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(datejText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(leveljText, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(idjText)
                                .addComponent(genderjText)
                                .addComponent(tinfojText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(emailjText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(createjLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(idjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idjLabel)
                    .addComponent(agejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejLabel)
                    .addComponent(namejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderjLabel)
                    .addComponent(genderjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(datejLabel)
                    .addComponent(datejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leveljLabel)
                    .addComponent(leveljText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tinfojLabel)
                    .addComponent(tinfojText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlejLabel)
                    .addComponent(titlejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contactjLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phonejLabel)
                    .addComponent(phonejText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailjLabel)
                    .addComponent(emailjText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(SavejButton)
                .addContainerGap(336, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void namejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namejTextActionPerformed

    private void idjTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjTextActionPerformed

    private void agejTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextActionPerformed

    private void tinfojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinfojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tinfojTextActionPerformed

    private void SavejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavejButtonActionPerformed
        // TODO add your handling code here:
        String name = namejText.getText();
        String id = idjText.getText();
        int age = Integer.parseInt(agejText.getText());
        String gender = genderjText.getText();
        String date = datejText.getText();
        String level = leveljText.getText();
        String info = tinfojText.getText();
        String title = titlejText.getText();
        String phone = phonejText.getText();
        String email = emailjText.getText();

       Details ds = history.addNewDetails();

        ds.setName(name);
        ds.setId(id);
        ds.setAge(age);
        ds.setGender(gender);
        ds.setDate(date);
        ds.setLevel(level);
        ds.setInfo(info);
        ds.setTitle(title);
        ds.setPhone(phone);
        ds.setEmail(email);

        JOptionPane.showMessageDialog(this, "Details Added!");

        namejText.setText("");
        idjText.setText("");
        agejText.setText("");
        genderjText.setText("");
        datejText.setText("");
        leveljText.setText("");
        tinfojText.setText("");
        phonejText.setText("");
        emailjText.setText(""); 

    }//GEN-LAST:event_SavejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SavejButton;
    private javax.swing.JLabel agejLabel;
    private javax.swing.JTextField agejText;
    private javax.swing.JLabel contactjLabel;
    private javax.swing.JLabel createjLabel;
    private javax.swing.JLabel datejLabel;
    private javax.swing.JTextField datejText;
    private javax.swing.JLabel emailjLabel;
    private javax.swing.JTextField emailjText;
    private javax.swing.JLabel genderjLabel;
    private javax.swing.JTextField genderjText;
    private javax.swing.JLabel idjLabel;
    private javax.swing.JTextField idjText;
    private javax.swing.JLabel leveljLabel;
    private javax.swing.JTextField leveljText;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JTextField namejText;
    private javax.swing.JLabel phonejLabel;
    private javax.swing.JTextField phonejText;
    private javax.swing.JLabel tinfojLabel;
    private javax.swing.JTextField tinfojText;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JTextField titlejText;
    // End of variables declaration//GEN-END:variables
}
